# Generated by Django 4.1 on 2022-09-23 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='عکس بندانگشتی')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='GetIpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آی پی ادرس')),
            ],
            options={
                'verbose_name': 'ای پی',
                'verbose_name_plural': 'ای پی ها',
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گراف')),
                ('graph_name_1', models.CharField(max_length=200, verbose_name='نام گراف 1')),
                ('graph_image_1', models.ImageField(upload_to='images', verbose_name='عکس گراف 1')),
                ('graph_number_1', models.IntegerField(verbose_name='مقدار گراف 1')),
                ('graph_name_2', models.CharField(max_length=200, verbose_name='نام گراف 2')),
                ('graph_image_2', models.ImageField(upload_to='images', verbose_name='عکس گراف 2')),
                ('graph_number_2', models.IntegerField(verbose_name='مقدار گراف 2')),
                ('graph_name_3', models.CharField(max_length=200, verbose_name='نام گراف 3')),
                ('graph_image_3', models.ImageField(upload_to='images', verbose_name='عکس گراف 3')),
                ('graph_number_3', models.IntegerField(verbose_name='مقدار گراف 3')),
                ('graph_name_4', models.CharField(max_length=200, verbose_name='نام گراف 4')),
                ('graph_image_4', models.ImageField(upload_to='images', verbose_name='عکس گراف 4')),
                ('graph_number_4', models.IntegerField(verbose_name='مقدار گراف 4')),
                ('graph_name_5', models.CharField(max_length=200, verbose_name='نام گراف 5')),
                ('graph_image_5', models.ImageField(upload_to='images', verbose_name='عکس گراف 5')),
                ('graph_number_5', models.IntegerField(verbose_name='مقدار گراف 5')),
                ('graph_name_6', models.CharField(max_length=200, verbose_name='نام گراف 6')),
                ('graph_image_6', models.ImageField(upload_to='images', verbose_name='عکس گراف 6')),
                ('graph_number_6', models.IntegerField(verbose_name='مقدار گراف 6')),
                ('graph_name_7', models.CharField(max_length=200, verbose_name='نام گراف 7')),
                ('graph_image_7', models.ImageField(upload_to='images', verbose_name='عکس گراف 7')),
                ('graph_number_7', models.IntegerField(verbose_name='مقدار گراف 7')),
                ('graph_name_8', models.CharField(max_length=200, verbose_name='نام گراف 8')),
                ('graph_image_8', models.ImageField(upload_to='images', verbose_name='عکس گراف 8')),
                ('graph_number_8', models.IntegerField(verbose_name='مقدار گراف 8')),
                ('graph_name_9', models.CharField(max_length=200, verbose_name='نام گراف 9')),
                ('graph_image_9', models.ImageField(upload_to='images', verbose_name='عکس گراف 9')),
                ('graph_number_9', models.IntegerField(verbose_name='مقدار گراف 9')),
                ('graph_name_10', models.CharField(max_length=200, verbose_name='نام گراف 0')),
                ('graph_image_10', models.ImageField(upload_to='images', verbose_name='عکس گراف 0')),
                ('graph_number_10', models.IntegerField(verbose_name='مقدار گراف 0')),
            ],
            options={
                'verbose_name': 'گراف',
                'verbose_name_plural': 'گراف ها',
            },
        ),
        migrations.CreateModel(
            name='ArticleHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.getipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graph', to='blog.graph', verbose_name='گراف'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='article', to='blog.articlecategory', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, through='blog.ArticleHit', to='blog.getipaddress', verbose_name='بازدی ها'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
